//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCalculation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartments
    {
        public Apartments()
        {
            this.MeterReadings = new HashSet<MeterReadings>();
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public decimal Area { get; set; }
        public byte ResidentsCount { get; set; }
        public short Floor { get; set; }
        public int BuildingId { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual ICollection<MeterReadings> MeterReadings { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
