//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCalculation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        public Buildings()
        {
            this.Apartments = new HashSet<Apartments>();
            this.BuildingFacilities = new HashSet<BuildingFacilities>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public short RegionId { get; set; }
    
        public virtual ICollection<Apartments> Apartments { get; set; }
        public virtual ICollection<BuildingFacilities> BuildingFacilities { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
