//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCalculation.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterReadings
    {
        public int Id { get; set; }
        public int ApartmentId { get; set; }
        public int ServiceId { get; set; }
        public int Value { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Services Services { get; set; }
    }
}
