//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCalculation.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentCalculationEntities : DbContext
    {
        public RentCalculationEntities()
            : base("name=RentCalculationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Apartments> Apartments { get; set; }
        public DbSet<BuildingFacilities> BuildingFacilities { get; set; }
        public DbSet<Buildings> Buildings { get; set; }
        public DbSet<InvoiceDetails> InvoiceDetails { get; set; }
        public DbSet<Invoices> Invoices { get; set; }
        public DbSet<MeterReadings> MeterReadings { get; set; }
        public DbSet<Regions> Regions { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Services> Services { get; set; }
        public DbSet<Tariffs> Tariffs { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
